In [41]:
import numpy as np
import torch

from enc import PE
from gaussian import Gaussian2D

scale = 1
mu = np.array([0, 0])
g = Gaussian2D(0, np.array([1, 1]), mu)

L = 12
pe_L = PE(d_in=2, n_freqs=L)
pe_2 = PE(d_in=4, n_freqs=2)

def enc(g: Gaussian2D):
    mu = torch.Tensor(g.position)
    cov = torch.Tensor(g.covariance_matrix())
    pos_enc = pe_L.encode(mu.unsqueeze(0), None)

    cov_feature = torch.flatten(torch.triu(torch.sign(cov) * torch.sqrt(torch.abs(cov))))
    cov_enc = pe_2.encode(cov_feature.unsqueeze(0), None)

    print(torch.flatten(torch.triu(torch.sign(cov) * torch.sqrt(torch.abs(cov)))))

    pass

enc(g)

tensor([[ 0.8415,  0.0000,  0.0000,  0.8415,  0.9093,  0.0000,  0.0000,  0.9093,
          0.5403,  1.0000,  1.0000,  0.5403, -0.4161,  1.0000,  1.0000, -0.4161]])
tensor([1., 0., 0., 1.])


In [43]:
covs = torch.randn(size=(10, 2, 2))
covs

tensor([[[ 0.6674, -1.2123],
         [ 0.1097,  0.5251]],

        [[ 0.7709, -0.0238],
         [ 0.2967, -0.0707]],

        [[-0.3423,  1.2686],
         [-0.3853,  1.0046]],

        [[-0.6151,  0.5545],
         [ 0.0457, -1.9108]],

        [[-1.0738,  0.2839],
         [-0.0073, -0.5824]],

        [[-0.3374, -0.3696],
         [ 0.3071,  0.5510]],

        [[-0.8764,  0.0171],
         [-0.1996, -0.4527]],

        [[ 0.3128, -1.4930],
         [ 0.6344,  0.2186]],

        [[ 0.2904, -0.1286],
         [ 0.6036, -0.5622]],

        [[-0.5464, -0.2503],
         [-0.2222,  0.5781]]])

In [63]:
torch.flatten(torch.triu(torch.sign(covs) * torch.sqrt(torch.abs(covs))), start_dim=1)


tensor([[ 0.8169, -1.1011,  0.0000,  0.7246],
        [ 0.8780, -0.1541,  0.0000, -0.2658],
        [-0.5851,  1.1263,  0.0000,  1.0023],
        [-0.7843,  0.7446,  0.0000, -1.3823],
        [-1.0362,  0.5328,  0.0000, -0.7632],
        [-0.5809, -0.6080,  0.0000,  0.7423],
        [-0.9362,  0.1308,  0.0000, -0.6728],
        [ 0.5593, -1.2219,  0.0000,  0.4676],
        [ 0.5389, -0.3587,  0.0000, -0.7498],
        [-0.7392, -0.5003,  0.0000,  0.7603]])